// Natural Earth land mask (ne_110m_land) rasterised onto an equirectangular
// COLS x ROWS grid and packed into bits, decoded back into a path in the
// browser. The poles are cut off, hence LAT_MIN / LAT_MAX.

export const COLS = 220;
export const ROWS = 82;
export const LAT_MIN = -58;
export const LAT_MAX = 76;

/** One bit per cell, row by row, north-west to south-east. */
export const LAND_MASK =
  "AAAAAAP43/gAP///wAAAAAAA4AAP/+AAPcAAAAAAAAPgT8lAAP//+AAAAAAAGAAf//7nAMAAAAAAAAB3/GH/AA///wAAAAAABwDe////+B/AAAAB/wAAB/HH/wB//8AAAAD4AAAd////////8ACA/////0gPMPAD//gAAAD/+AJe7///////////A////////wfgf/gAAAA//+X//f//////////OP///////8D6A/wA+AAH5+P/////////////8AD//////+eDwD+ABgAA/P///////////////gB///////gHhADwAAAAf5///////////////4AH/n////8AHgADAAAAB/n/////////////h+AAHwB////4A/IAAAAAAHeP///////////4IYAAAEgA////4B/wAAAAA4Bxf//////////+ADwAABAAB////8H/gAAAABgWH///////////gAeAAAAAAB////8//gAAAAzB3////////////QBwAAAAAAT////z//AAAADef/////////////QGAAAAAAAH//////0AAAABn/////////////9AAAAAAAAAX/////Q4AAAAB//////////////wAAAAAAAAA//////AwAAAAP/////////////+AAAAAAAAAD/////+gAAAAAf//yf/////////wAAAAAAAAAP/////IAAAAAB+3/A/////////+MAAAAAAAAA/////4AAAAAB/Fn4B/////////BQAAAAAAAAD/////AAAAAAHwRuv/////////4CAAAAAAAAAP////wAAAAAA/BAz/////////JAIAAAAAAAAAf///+AAAAAAB4AhH////////+GBAAAAAAAAAA////8AAAAAAAPwAA////////8YcAAAAAAAAAB////gAAAAAAP/AAD////////gJAAAAAAAAAAD///4AAAAAAD//hAf////////BgAAAAAAAAAAF///AAAAAAAP//Pp////////8AAAAAAAAAAAAH/yEAAAAAAA/////+f//////4AAAAAAAAAAAAv+AYAAAAAAP////P8///////AAAAAAAAAAAABf4AgAAAAAB////+/4f/////4AAAAAAAAAAAAA/AAgAAAAAH////9/mB/////AAAAAAAAAAAAAB8AYAAAAAA/////z/8D////5AAAAAAAAAAAAAD4YIAAAAAD/////v/wH/j/0AAAAAAAAAAAAAAPhAGAAAAAP////+f+AH8H+QAAAAAAAAAAAAAAf8CJAAAAA/////5/wAfgP4AgAAAAAAAAAAAAAPwAAAAAAD/////z8AB8AvwCAAAAAAAAAAAAAAD4AAAAAAf/////vAAHgA/gAAAAAAAAAAAAAAABgAAAAAA//////wAAOAC+AQAAAAAAAAAAAAAAGBQAAAAD/////8IAA4AJ4AgAAAAAAAAAAAAAAIN8AAAAH//////gABAAiAkAAAAAAAAAAAAAAAL/8AAAAP/////+AAFACAAYAAAAAAAAAAAAAAAH/4AAAAf/////wAAEAEAQgAAAAAAAAAAAAAAAf/8AAAAyH///+AAAADYDAAAAAAAAAAAAAAAAB//4AAAAAD///4AAAAGgcAAAAAAAAAAAAAAAAP//gAAAAAP//+AAAAANHwAAAAAAAAAAAAAAAB//+AAAAAA///wAAAAAYfAAAAAAAAAAAAAAAAH///gAAAAD//+AAAAAAx5gQAAAAAAAAAAAAAAf///wAAAAP//4AAAAADjmd+AAAAAAAAAAAAAD////gAAAAf//AAAAAAGAQA+AAAAAAAAAAAAAH////gAAAA//8AAAAAAEAAB8AAAAAAAAAAAAAP///+AAAAD//wAAAAAADAAPYEAAAAAAAAAAAA////wAAAAP//AAAAAAAAQAAwAAAAAAAAAAAAB///+AAAAA//+AAAAAAAAAAAAAAAAAAAAAAAAH///wAAAAD//4AAAAAAAADhAAAAAAAAAAAAAAP///AAAAAf//hgAAAAAADeGAAAAAAAAAAAAAAf//8AAAAB//8cAAAAAAAP84AAAAAAAAAAAAAAf//wAAAAH//hwAAAAAAB//gAAIAAAAAAAAAAB///AAAAAP/4HAAAAAAAP//AAAAAAAAAAAAAAH//4AAAAA//gcAAAAAAH//+AAAAAAAAAAAAAAf//AAAAAB//BgAAAAAA///8AAAAAAAAAAAAAB//gAAAAAH/4GAAAAAAH///4AAAAAAAAAAAAAH/8AAAAAAf/AAAAAAAAf///wAAAAAAAAAAAAAf/wAAAAAA/8AAAAAAAA////AAAAAAAAAAAAAD//AAAAAAD/gAAAAAAAD///8AAAAAAAAAAAAAP/4AAAAAAH8AAAAAAAAH///wAAAAAAAAAAAAA//AAAAAAAfgAAAAAAAAfg/+AAAAAAAAAAAAAD/YAAAAAABgAAAAAAAADgA/wAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAAAAAB/AAIAAAAAAAAAAB/4AAAAAAAAAAAAAAAAAAAD8AAQAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAfQAAAAAAAAAAAAAAAAAAAAIAAUAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAQABAAAAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

export function isLand(bytes: Uint8Array, index: number): boolean {
  return (bytes[index >> 3]! & (1 << (7 - (index & 7)))) !== 0;
}

export function decodeMask(): Uint8Array {
  const binary = atob(LAND_MASK);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

export function toGridCell(lon: number, lat: number): { x: number; y: number } {
  return {
    x: ((lon + 180) / 360) * COLS,
    y: ((LAT_MAX - lat) / (LAT_MAX - LAT_MIN)) * ROWS,
  };
}
